### PR TITLE
Preparing sf5 compatibility

### LINKED ISSUE #227: Symfony 5.0 support
Do you plan to support symfony 5.0?

### PR DESCRIPTION
**Pull request by Spomky**
Will fix #227

### CODE REVIEW

**Comment by lucasvanlierop** [comment]
Nice, thanks!, I'll give this a try tomorrow!

**Comment by rderocle** [comment]
Hi guys, is the project available for symfony 5? I have a composer message when I try to install :

`
➜  api git:(master) ✗ composer require web-token/jwt-framework:"^2.1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - web-token/jwt-framework v2.1.1 requires symfony/config ^4.2 -> no matching package found.
    - web-token/jwt-framework v2.1.0 requires symfony/config ^4.2 -> no matching package found.
    - Installation request for web-token/jwt-framework ^2.1 -> satisfiable by web-token/jwt-framework[v2.1.0, v2.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by Spomky** [comment]
Hi @monsieurchico,

It is not yet tagged. This should be done by the end of the week.

**Comment by rderocle** [comment]
Okay thanks ;)

**Pull request merged**
