### PR TITLE
#207 JWKSource for p12 files

### PR DESCRIPTION
**Pull request by unixslayer**
#207

### CODE REVIEW

**Comment by Spomky** [comment]
Thank you. That's a nice addition!
It looks like I forgot this use case.

**Comment by unixslayer** [comment]
@Spomky about this PR, should I bother with Travis and coveralls? Travis fails because of core code which wasn't changed in PR. Also coverage decrease seems irrelevant with 0.043% ;)

**Comment by Spomky** [comment]
Don't worry about the failing tests. I will soon close this PR, but integrate it in the v2.1 branch (the branch master is not appropriate for this new feature).

**Comment by unixslayer** [comment]
@Spomky I think I've messed up something when changing base branch. Will do this PR again this time from proper branch.

**Pull request closed without merging**
